export const ADD_COMMENT = 'ADD_COMMENT';
export const FETCH_COMMENTS_START = 'FETCH_COMMENTS_START';
export const FETCH_COMMENTS_END = 'FETCH_COMMENTS_END';
export const GET_COMMENTS = 'GET_COMMENTS';

export const EM_CLICK_LINK = 'EM_CLICK_LINK';